### ISSUE TITLE
Is this project still being developed?

### ISSUE THREAD

**Issue by petterreinholdtsen** [aclements/libelfin#10]
Hi.  As you might have seen, I am considering to include this library into Debian, as a dependency for the Coz profiler.  But the old pull request with not followup for almost a year and the old issue with no reply since December last year make me worried.  Is this library still being developed?

The reason is that it is a lot more work to take over a library with no active development than it is to just package a well maintained software system for Debian.

**Comment by aclements** [comment]
It is my intention to maintain libelfin and keep it building and working. I actually had fixed the issue from December, I just somehow failed to close it (thanks for the reminder :). The PR was my bad; I'm still trying to find a code review system for GitHub that I don't hate.

That said, I am no longer *developing* libelfin, since nothing that I'm working on these days depends on it (and ELF and DWARF change pretty slowly). I would be happy to hand over development to someone I trust if someone is interested (@ccurtsinger?).

**Comment by petterreinholdtsen** [comment]
Good to hear.  Then we will move forward with our plan to get it into Debian.

**Comment by petterreinholdtsen** [comment]
I'm happy to report that libelfin entered Debian today, see https://tracker.debian.org/pkg/libelfin .  It would be very nice with a new release building shared libraries.
